// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rainbow.Database;

#nullable disable

namespace Rainbow.Migrations
{
    [DbContext(typeof(RainbowContext))]
    [Migration("20211224012007_FlagGuildList")]
    partial class FlagGuildList
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rainbow.Entities.FlaggedUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("FlagReason")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FlaggedUser", (string)null);
                });

            modelBuilder.Entity("Rainbow.Entities.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("FlaggedUserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("FlaggedUserId");

                    b.ToTable("Guild", (string)null);
                });

            modelBuilder.Entity("Rainbow.Entities.GuildConfiguration", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Prefix")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GuildConfiguration", (string)null);
                });

            modelBuilder.Entity("Rainbow.Entities.Guild", b =>
                {
                    b.HasOne("Rainbow.Entities.FlaggedUser", null)
                        .WithMany("FlagGuilds")
                        .HasForeignKey("FlaggedUserId");
                });

            modelBuilder.Entity("Rainbow.Entities.FlaggedUser", b =>
                {
                    b.Navigation("FlagGuilds");
                });
#pragma warning restore 612, 618
        }
    }
}
